/* Calculator.java */
/* Generated By:JavaCC: Do not edit this line. Calculator.java */
package edu.wallawalla.cs.cptr354.interpreter;

import static org.junit.Assert.assertEquals;

import java.io.StringReader;

import org.apache.asterix.lang.sqlpp.parser.Calculator;
import org.junit.Test;

public class CalculatorTests {
	@Test
	public void testAddition() throws Exception {
		String inputString = "5 + 6\n";
		String result = ConsoleInterceptor.copyOut(() -> {
			Calculator cal = new Calculator(new StringReader(inputString));
			cal.parseOneLine();
		});
		assertEquals("11.0\n", result);
	}

	@Test
	public void testSubtraction() throws Exception {
		String inputString = "5 - 6\n";
		String result = ConsoleInterceptor.copyOut(() -> {
			Calculator cal = new Calculator(new StringReader(inputString));
			cal.parseOneLine();
		});
		assertEquals("-1.0\n", result);
	}

	@Test
	public void testMultiplication() throws Exception {
		String inputString = "5 * 6\n";
		String result = ConsoleInterceptor.copyOut(() -> {
			Calculator cal = new Calculator(new StringReader(inputString));
			cal.parseOneLine();
		});
		assertEquals("30.0\n", result);
	}

	@Test
	public void testDivision() throws Exception {
		String inputString = "30 / 6\n";
		String result = ConsoleInterceptor.copyOut(() -> {
			Calculator cal = new Calculator(new StringReader(inputString));
			cal.parseOneLine();
		});
		assertEquals("5.0\n", result);
	}

}
